language: java
os: linux
sudo: false # faster builds

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

jdk: openjdk8

install: skip

script:
  - echo "TRAVIS_TAG ${TRAVIS_TAG} - TRAVIS_BRANCH ${TRAVIS_BRANCH}"
  - ./gradlew build

deploy:

  - provider: bintray
    skip_cleanup: true
    file: "build/bintray-deploy-descriptor.json"
    user: boddissattva
    key:
      secure: G8rXzZ+z+E0KD4R3hO4EnRQweczB8JCIUB12PiBEa+85qzGGjG07ilzGTZjSutueU4iTu2N39G+MFvYC+vyqV1ufb5/CqkGin9yb3MfGwntN0HMWg4j6ODEQ5Af9vwoqHgJYu0ch3GiklNIA2AVppGM7ECqssouEJxdNzKYVolXTpRqMbaRnFXFi8ir2pVwv71zq9GkpfnOaCef3AsZ3AdOlPXzhmQoh2ORZbsFk3mr81OYiPQgvgAme/gw9uZPDBOn2XrzF8Vk5LAh+cJmN4LixDXflaHZg9MsJdboWpFKksDzw7vHnjcintxbQmolC1p45OQSbxvCsTR1JjeZ/+5fWSEGppIgUy2+ADxR/n+CRuhl6o4Q96LqFKo/aOzlenhxE1TzdV7tdEpsHTfFzXOAO7hr6gtYNAwSB/XoslFWyUHxETxUaZk9MQ6o/tBFcwDylGWEjiUKeY8dHvthnQL+EMJUvgbtE1+LzVTX7IimjpyEHU0pbNJmxugn1ZPaNGtsTpnWEfF5n8f0GeN8s1rgRn3w9vlnr74rNGC8uQf4rn2cb8dGlsksRznZOV1jKQJIWXwrXWGMzs0sX/lVtnw/tZCeYzVcELQQyWcEENz3zddlRGxtMVxZpYiaBarOrK0iomjsp7WaNaZUKGzsxUMIGESQkLE0od5WB2UAV3n0=
    on:
      repo: chutney-testing/chutney-kotlin-dsl
      branch: master
      tags: true

  - provider: releases
    skip_cleanup: true
    file_glob: true
    file: "build/libs/*.jar"
    api_key:
      secure: PomXiVGmmaZRg+pjS7hTG9X+WaBaTkVjTwXkua/HNn7eRdweNz2gSMOjBRiuzADS/q/s2zuB4JVhX87BJ2r1/93NZtvs0UwdUTeectfdshJocQYBpS5oDpWUnOeKTkOpZTsTLXXneJ95y8z3Ai+L6urlQTACLlWJ1ZaDnk4+TlDyEW3OZPZKrY6qltHTE+niSlXdEtfri+qExUR5hFM5JOHqYtc3Qzmv/fJrL9Smk9O4a+5piBwdJQN2KoTM0BIduViboOw+YcakkIY9TyCpOCsqhLoGx1IV20h+jfzC/JBm+tpFfAXLWgDQsP/XV3dFkhzEbwWqzABfuVjnUakz81DFzgK9whdTKOIqwIzySUrKhJg/FHaoNYUXmjNCggoeFp4mjLcOuWEhV+bJTWhGMMWxC7Vm7gsSGvmXDILQ51RiPnEDlv/HemS/TzMaAbBz+ic3Y+3Ib0dC0RuWJcs7J94DHY2IuX9FiYdRg2RZ0mcFd3Yx/SISxQGGRkWxqadwc4evKF9Tp7cwdbSVcGlPq4dzp8kMHbvCn7SRhKFNOW7oZg79BIF5vuMw4jdc1WkGCbwfCCrklkAO/VzcE0Kk65+7JW8zW94KiVJtbkL8NyoWMiD+ki54neiBp+5OzpneHv7MNnK3s0ITlCPrRNMeF1/CV2YOuBiBoDq1tUG8vjQ=
    on:
      repo: chutney-testing/chutney-kotlin-dsl
      branch: master
      tags: true

notifications:
  webhooks:
    - secure: "lVxOUn5+AVbN182QhrKpDZm5BXyRS0rkNE5zHWy9GS1F0ozrXTS1kYuTmMFKWuhwZ3Fj252tMxT772XFdKy72vdOMEA1KCBoKM9bcPfRC9MA8oslhUXjoOv+c+4hQrzyeowyycaXU2AheYV5V+zASxyEOQnH+uZVrxqv2iORCt72d0I7q9XDRRZwCNAIAXBCn4RFbHkcYqXc2sllY1JOuQ0F/1+1V3Xj9FbVVVs6EyQNnLvcw/veExrd7R2xlLz+/V3FQZjAd625gxfwmR9kNEgv9czLqVnawVsh31s14uLOk2R8uy+IjLW6fATgvWrfTOA/FmKo/jBrA/rlA8eHrNRwIfYFv21GOpycsxjVm3XaNSbt4GfxfWK+ZDvZriPdPgoyQJ5+RBWOwD84N+Zkeu/Ldj1paFFXvGXnfhXHwhRZAzCZhXHMkETTr5Cp7Sc/govDREWoC6gfQfoT6EnUlz3PyfdO5Oi0XCs/5xP7v2S4qbzC17ycmaKVUBwqPXzk8e6HqtcbI/c6gFi7oVl7vkC7giyDKc68JWnJx9HdvYpMzxNdMbGlcA8bcGoO0uKR6/Fp6j6DVa36664Tz5+FErqoOU1DjWF0N9IwFEHWlMn70wqWtTvh50eFtLD+XBD0jVM+PQdjwehesPD5AC208dHida9ziGbl0xjC/6bXHU0="
