language: java
os: linux
sudo: false # faster builds

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

jdk: openjdk8

install: skip

script:
  - echo "TRAVIS_TAG ${TRAVIS_TAG} - TRAVIS_BRANCH ${TRAVIS_BRANCH}"
  - ./gradlew build

deploy:

  - provider: bintray
    skip_cleanup: true
    file: build/bintray-deploy-descriptor.json
    user: boddissattva
    key:
      secure: OYmEl3SCbV+qjlQopexAX5Ur3zraKMT/GB7tPtK6WTEhTFYPc7n06Iyf29qBrKVhsi3cAyVsAs6r+okCbaLlL0LLbHjHI+09qeXclbieWMOK15Y9lF+nLZtD+6m/hcqAAHcpAXDPAO6ErrsvEebcz+bJuQ9euKXpy9UIjgEfxphg+vNpuG0SEIDdaPIV0us0Jbr1ddQvur/eF7nLbW8z+9/9MIWkz59tl57DW4lROVRIeR2YfHdWuSnEa8Tpx0HmHkfox8hzqPw7xkGt3pSy9Sp9DqtLp76VhB6ppf3KxgY2Z8CNVPZDiecQtOg8lEnV0HEFB1vefFpacqB/V4Xzldelq2f+exzAL83QuQGPjn70k6SbVqvR3IOMCfalRaszK2d2dgbQxNaVdOU45JYk3XB/7W+nTwOCdOT17nV9GQGs4ZmNyMSjim/kOGMM1dJVcXf+sf6SfO6v6ZI/QFmEKUdd39N7DmAGJFtE67ISD3wMvKGe4PnzE32ADXMS2jmRV466xynjwH1Ae4UV+gkBCqO3U0OplA1QmwcFixfGifeRE22uv6t4jImutme8LkJygWXORVcR02IPYcQhfPqE5h49nCQeqHUgZIdYYOIzAJsg5vR/4zRAxISe9tHnlklMPN1w/9ljohbV6IKPFXhESbshra3rCIoHEdTMr2LiLdc=
    on:
      repo: chutney-testing/chutney-kotlin-dsl
      branch: master
      tags: true

  - provider: releases
    skip_cleanup: true
    file_glob: true
    file: build/libs/*.jar
    api_key:
      secure: bAOKVhVMAEgA6mShKiqgjY01wqCcgO/Ueow6COb/qh50w2WnUQKEkSbT4zvWe3gLUqUxmXKWHnt9VEUk/TGcksLI+lzshnL2DSCLLuh+RchaBdOdyhDCPNWS4x2YnxBfBubyEFWcKXUQ77ekUHZZf8WeZ4BkKwkdcTxzvWZGQ+R1yHaitWFqrVj0Yk1EEfKM6jaubQsP7Say1K4ArrzW7yn5cXXHsx/hLQm1LhrHGfEYSwNfDPrQq+6l1LYE3mUe0F4FGd8NFgWEXLHR6qyG2Cl1XJ9ickYlAbc4XtGwbLcuMtPrKoQpfA2XYxheZWmwPORbwfucLOewByIEekL1SykO+akJLt0VYdV5J/Yz00SJUpEriDHP9RJWYy5mzqGmSIx5eA5P9zcqKY1TsajxtR4ya/dnfRUJ+1G71cyC2Rfz5l8qvMvlH0/EYmIl3hqVCsCRV8eaC0x/2ztFFsotl4LSAU9VtzNQD6fg5hNQ5f9hlVzX0sNTuaoQlwRnxphUwOG/VXlWBYXDjkYZEvIxMiD0HDn2euubYVPEsadLLcS8MktPe9gJhVlntdAEBvec1gDkjTDEarFmiK+Dwcf8DRFU44ArZ6FoJB8EQllhJp6mfNmgVl/EJxeQ+St0gG2GTR6haoRyuGO2Z9gZB/SE+5BlyWAn+SQ79sr3I4f4jhg=
    on:
      repo: chutney-testing/chutney-kotlin-dsl
      branch: master
      tags: true
