name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    name: Deploy to central
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Verify the project build
        run: ./gradlew build

      - name: Publish to OSSRH
        run: ./gradlew publish
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          CHUTNEY_GPG_KEY_ID: ${{ secrets.CHUTNEY_GPG_KEY_ID }}
          CHUTNEY_GPG_KEY: ${{ secrets.CHUTNEY_GPG_PRIVATE_KEY }}
          CHUTNEY_GPG_PASSPHRASE: ${{ secrets.CHUTNEY_GPG_PASSPHRASE }}
