name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Verify the project build
        run: ./gradlew build
      - name: Publish artefact on bintray
        run: ./gradlew bintrayUpload
        env:
          BINTRAY_SERVER_USERNAME: ${{ secrets.BINTRAY_SERVER_USERNAME }}
          BINTRAY_SERVER_PASSWORD: ${{ secrets.BINTRAY_SERVER_PASSWORD }}
